function sim=Init_sim
global sim;

sim = struct( ...
    'flag',1,... %flag=0代表UMi，flag=1代表UMa
    'intersitedistance',500,... %站间距500m%%系统配置         
    'sitenum',19,...  %初始化7个小区,取7,19等，一圈一圈地加
    'cellnum',57,...  %扇形区数目
    'raynum',20,...   %每簇子径数
    'hbs',25,...  %基站天线高度
    'Gain',49,...   %基站发射功率dBm
    'mind2d',10,... %终端到基站的最小2D距离
    'wrap_offsetx',[0 4 7/2 -1/2 -4 -7/2 1/2],...%单位为intersitedistance
    'wrap_offsety',[0 sqrt(3) -3*sqrt(3)/2 -5*sqrt(3)/2  -sqrt(3) 3*sqrt(3)/2 5*sqrt(3)/2],...%单位为intersitedistance
    'usernumpersite',5,...
    'RISnumpersite',1,...%RIS数量设置
    'userlistcoorx',zeros(1,570),...%用户坐标
    'userlistcoory',zeros(1,570),...
    'hut',25,...%终端天线高度
    'Qx',zeros(1,570),...%用户初始角度
    'Qy',zeros(1,570),...
    'Qz',zeros(1,570),...
    'bandwidth',10,...% in MHz
    'RB_num',75,...
    'cluster_size',3,...
    'iter_times',1+4,...
    'sinrthreshold',-6,...
    'fc',6*10^9, ...
    'RIShut',15, ...
    'compthreshold',3 ...%中心频率 
    );



